apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: staging
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
