apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: staging
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
