apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: satishgoli6011/cast-service:dev
          ports:
            - containerPort: 8001 
